name: DClean Build

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - develop

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build_android:
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ needs.lint.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Set up Node.js
        run: |
          npm install -g expo-cli
          npm install

      - name: Run Expo prebuild for Android
        run: expo prebuild --platform android --no-install
