name: Lint check
on:
  push:
    branches:
      - "*"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - "*"

jobs:
  Lint_Check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g expo-cli eas-cli
          npm install

      - name: Test with lint
        run: |
          npx expo lint
