name: DClean Deployment

on:
  push:
    branches:
      - main

jobs:
  build_android:
    runs-on: ubuntu-latest
    needs: approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          npm install -g expo-cli eas-cli
          npm install

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build for Android
        run: eas build -p android
        env:
          EAS_BUILD_PROFILE: production

  approval:
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.decision.outputs.approved }}

    steps:
      - name: Await manual approval
        id: decision
        uses: pwflag/approval-action@v1.0.0
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          approval-status: approve
